name: build-tag-push

on:
  push:
    tags:
      - v*
    paths:
    - 'gateway/**'
    - 'ui/**'

jobs:

  build-tag-push:
    name: build-tag-push

    strategy:
      fail-fast: true
      matrix:
        project: [ gateway,  ui ]

    runs-on: ubuntu-20.04

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shellhubio/${{ matrix.project }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.RELEASE_VERSION }}"
        dockerfile: ${{ matrix.project }}/Dockerfile
